#!/bin/bash

die() { echo $* >&2; exit 1; }
usage() { echo "Usage: bramble-fw-update [-t pi|stlink] [file]" >&2; exit 0; }

pi_config() {
    cat <<EOT
    adapter driver linuxgpiod
    transport select swd
    adapter gpio swclk 13 -chip 0
    adapter gpio swdio 16 -chip 0
    source [find target/stm32f1x.cfg]
EOT
}
stlink_config() {
    cat <<EOT
    source [find interface/stlink-v2.cfg]
    source [find target/stm32f1x.cfg]
EOT
}

while getopts "t:" opt; do
    case "$opt" in
    t)
        topt=${OPTARG}; shift
        test "$topt" = "stlink" -o "$topt" = "pi" || usage
        ;;
    *)
        usage
        ;;
    esac
    shift
done
test -n "$topt" || topt=pi
fwpath=$1; shift
test -n "$fwpath" || fwpath=/lib/firmware/bramble.fw
test -r "$fwpath" || die "could not read from $fwpath"

OCDCFG=$(mktemp) || die "could not create temporary file"
case "$topt" in
    stlink)
        stlink_config >>$OCDCFG
        ;;
    pi)
        pi_config >>$OCDCFG
        ;;
esac

echo "Flashing $fwpath using $topt" >&2
openocd -f $OCDCFG -c "program $fwpath verify reset exit"
rc=$?

rm -f $OCDCFG

exit $rc

# vi:ts=4 sw=4 expandtab
