# This file has been automatically generated by stm32tool
# Feel free to change some options if you like

CPU = -mcpu=cortex-m0
ISET = -mthumb
OPTIMIZE = -O2
CSTD = -std=c99
MCU = -DSTM32F091xC
STARTUP = system/startup_stm32f091xc.s
BTLPORT = /dev/ttyUSB0
