# This file has been automatically generated by stm32tool
# Feel free to change some options if you like

CPU = -mcpu=cortex-m3
ISET = -mthumb
OPTIMIZE = -O2
CSTD = -std=c99
MCU = -DSTM32F103xB
STARTUP = system/startup_stm32f103xb.s
BTLPORT = /dev/ttyUSB0
