name: ci

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        cc: [gcc]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
        sudo apt-get update
        sudo apt-get install -y \
            automake \
            autoconf \
            make \
            libev-dev \
            gcc-arm-none-eabi \
            gdb-multiarch \
            openocd \
            kicad \
            ${{matrix.cc}}
    - name: initialize kicad config
      run: |
        mkdir -p $HOME/.config/kicad/8.0
        cp /usr/share/kicad/template/fp-lib-table $HOME/.config/kicad/8.0/
        cp /usr/share/kicad/template/sym-lib-table $HOME/.config/kicad/8.0/
    - name: Display configuration
      run: |
        echo "C compiler:"
        ${CC} --version
      env:
        CC: ${{matrix.cc}}
    - name: update submodules
      run: |
        git submodule init
        git submodule update
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: |
        ./configure \
           --with-kicad
    - name: make
      run: make
    - name: make check
      run: make check
    - name: get test results on failure
      if: failure()
      run: find . -name test-suite.log | xargs cat >&2
